### ISSUE TITLE
different behavior of methods

### ISSUE THREAD

**Issue by cultulhul** [dszczyt/hapi-pg-promise#11]
when i user oneOrNone and the query returns no data in the then promise data is empty but when i use manyOrNone or any data is an empty object

**Comment by robertpallas** [comment]
@cultulhul did you try catch? `oneOrNone` expects 1 or no results. `manyOrNone` is same as `any` and accepts all answers. My guess is your query returns more than one result. Need example code.

In any case this is not a bug and if it was it would not be in this package. This package is a way to conveniently add pg-promise to your Hapi app. Query methods are part of [pg-promise](https://github.com/vitaly-t/pg-promise).

**Comment by cultulhul** [comment]
thanks the query was returning more than one row
