### ISSUE TITLE
How to use with pg-monitor?

### ISSUE THREAD

**Issue by sebastianhelbig** [dszczyt/hapi-pg-promise#13]
How can this be used together with pg-monitor? My solution is by adding pg-monitor inside hapi-pg-promise, as seen here: https://github.com/ro14-sh/hapi-pg-promise/commit/b6f3fe08a991731f3f63be61eff6f01e0d75440c
Is there another solution?

**Comment by vitaly-t** [comment]
Try via the [$config](http://vitaly-t.github.io/pg-promise/Database.html#$config) property of the `db` object:

```js
const monitor = require('pg-monitor');

monitor.attach(db.$config.options);
```
