### ISSUE TITLE
hapi should be a peer dependency

### ISSUE THREAD

**Issue by thedark1337** [dszczyt/hapi-pg-promise#2]
I noticed that there was a dependency on 11.x of hapi. [12.x](https://github.com/hapijs/hapi/issues/2985) was recently released so now I have both 11.x and 12.x installed in my node_modules. Also, there were a few vulnerabilities as it shows in david-dm. Perhaps move it to peerDependencies & devDependencies ?

**Comment by dszczyt** [comment]
I published the package on npm. It should be OK now. Feel free to reopen if anything's wrong.
Thanks.
